apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: false
    pairs:
      flux.zondax.io/bootstrapping: flux-demo
      flux.zondax.io/src: flux-demo
      flux.zondax.io/component: bootstrap
resources:
  - apps.yaml
